### ISSUE TITLE
Literature Box

### ISSUE THREAD

**Issue by jgrethe** [NeuroscienceKnowledgeSpace/KnowledgeSpace#1]
For the literature box - can we have the latest publications be listed as well - in addition or instead of the literature graph?

-Sean

**Comment by jgrethe** [comment]
One way to do this would be to have a little toggle on the literature box that could be either graph or listing.  We could default to one initially and users could switch the default (just be what the select on the toggle - i.e. it renders the last option chosen by the user)...

**Comment by wawong** [comment]
Sure, I will add a toggle button to the literature panel.

-Willy

**Comment by tgbugs** [comment]
We should default to listing the publications. In addition we should not render the number of publications for the current year.

**Comment by wawong** [comment]
Created tabs for the most recent publications and the year graph.
