### ISSUE TITLE
do not hide the search box

### ISSUE THREAD

**Issue by tgbugs** [NeuroscienceKnowledgeSpace/KnowledgeSpace#11]
Currently there is a bug where clicking on the search button (magnifying glass) opens the search box but does not move the cursor to the box. We could fix this, however, we have dead space at the top of each entry to the left of 'About' and there is really no good reason to hide the search box at all, it is just one more thing the users have to learn. We should have an always-visible search box at the top of the page between the logo and the 'About' button.

**Comment by wawong** [comment]
The search bar now is always in the navigation bar.
