### ISSUE TITLE
dataspace search errors

### ISSUE THREAD

**Issue by tgbugs** [NeuroscienceKnowledgeSpace/KnowledgeSpace#14]
https://nye.crbs.ucsd.edu/NeuroKS/index.php/Results/view/nlx_154697-8/Piriform%20area,%20pyramidal%20layer/1

Causes an error, probably due to the comma?

Do we do synonym expansion here? (I have a feeling this is related to the scigraph/ontoquest issue)

**Comment by wawong** [comment]
%2c is replaced with "," in the URL
https://nye.crbs.ucsd.edu/NeuroKS/index.php/Results/view/nlx_154697-8/Piriform%20area%2c%20pyramidal%20layer/1

**Comment by wawong** [comment]
The latest version should return results with %2c instead of "," in the URLs. The comma is still illegal in the URI.
