### ISSUE TITLE
release TODO

### ISSUE THREAD

**Issue by tgbugs** [NeuroscienceKnowledgeSpace/KnowledgeSpace#15]
1. capitalize the first word of the name at the top of each page
 2. put dataspace above the relations

**Comment by tgbugs** [comment]
3. remove images box if there are no images

**Comment by wawong** [comment]
1. Capitalize the first word -- Done
2. Put dataspace above the relations -- Done.

**Comment by tgbugs** [comment]
\4. Documentation page needs a link to
https://github.com/NeuroscienceKnowledgeSpace/ksdesc
and
https://github.com/SciCrunch/NIF-Ontology

**Comment by wawong** [comment]
Added both https://github.com/NeuroscienceKnowledgeSpace/ksdesc and
https://github.com/SciCrunch/NIF-Ontology

What description should I put for https://www.trelliscience.com/#/group-home/504 ?

**Comment by tgbugs** [comment]
@wawong for the trellis page, I would put `KnowledgeSpace working group homepage`
