### ISSUE TITLE
summary textbox needs to source the markdown entries in ksdesc

### ISSUE THREAD

**Issue by tgbugs** [NeuroscienceKnowledgeSpace/KnowledgeSpace#3]
What is the roadmap for editable entries? In particular the summary text box.

We need to start sourcing the markdown files here: https://github.com/NeuroscienceKnowledgeSpace/ksdesc/ for the summary box.

We also need to put a link in the box to the file that backs it, OR if it does not exist we need to take the user to the github page to create that entry.

**Comment by tgbugs** [comment]
The summary box sources data from this repository: https://github.com/NeuroscienceKnowledgeSpace/ksdesc

I can write up a doc for how to contribute a page using the github user interface.

**Comment by tgbugs** [comment]
https://github.com/erusev/parsedown

**Comment by wawong** [comment]
Done. Test it with https://nye.crbs.ucsd.edu/NeuroKS/index.php/pages/view/PR:000000707
