### ISSUE TITLE
Error upon GET query request: No 'Access-Control-Allow-Origin' header is present

### ISSUE THREAD

**Issue by Tsolmongerel** [NeuroscienceKnowledgeSpace/KnowledgeSpace#30]
We are working on integrating brain atlas viewer with KnowledgeSpace. When we request from the atlas viewer application, we are getting this error:

> XMLHttpRequest cannot load https://knowledge-space.org/NeuroKS/index.php/API/summary/MBA:549. No 'Access-Control-Allow-Origin' header is present on the requested resource.

Javascript example code piece is as following:
```
var resource = $resource('https://knowledge-space.org/NeuroKS/index.php/API/summary/MBA:549');
        $scope.example1 = resource.get();

        resource.get().$promise.then(function(value) {
            $scope.example2 = value;
        });
```

Since we would like to integrate the atlas viewer with summary information from KnowledgeSpace, this issue is blocking.

**Comment by wawong** [comment]
Hi Tsolmon,

I set the header to allow all cross domain requests for now. I tested it and it's working on my javascript code. Let me know whether it's working for you too. In future, we should consider whether we allow all cross domain requests.

Thanks,
Willy
