### ISSUE TITLE
Need https access to site in order to integrate with HBP collaboratory

### ISSUE THREAD

**Issue by tgbugs** [NeuroscienceKnowledgeSpace/KnowledgeSpace#4]
hbp collaboratory, everything is released there, to access it, possible to add links there, for this to work, it goes in an iframe, the connection needs to be https with a good cert

**Comment by tgbugs** [comment]
Could I get someone to elaborate on this?

**Comment by tgbugs** [comment]
Hi all, https is implemented, and the site has a certificate. We are unable to reproduce the certificate issue on our end. Do you have a repro for this so that we can try to track it down?

**Comment by wawong** [comment]
Few weeks ago, we added the certificate for the knowledge-space.org domain name. See https://knowledge-space.org/   . Tom, can you check with the hbp team?

**Comment by tgbugs** [comment]
This is working now.
