### ISSUE TITLE
formatting of text in the data view

### ISSUE THREAD

**Issue by tgbugs** [NeuroscienceKnowledgeSpace/KnowledgeSpace#5]
Formatting on some data views is a bit wonky, for example:
https://nye.crbs.ucsd.edu/SciCrunchKS/index.php/Results/view/nif-0000-37639-1/Schwann%20Cell/1

The text probably shouldn't be centred but instead should be at the top of each of the cells.

**Comment by wawong** [comment]
It should align the text to the top now.

**Comment by wawong** [comment]
It should align the text to the top now.
