### ISSUE TITLE
traverse alternate hierarchies in the relations window

### ISSUE THREAD

**Issue by tgbugs** [NeuroscienceKnowledgeSpace/KnowledgeSpace#6]
We need to show other relationships besides subClassOf for things like anatomical entities where we want the user to be able to explore through the brain partonomy (for example).

**Comment by tgbugs** [comment]
subClassOf
http://purl.obolibrary.org/obo/BFO_0000050
http://www.obofoundry.org/ro/ro.owl#has_proper_part

#do not use these
http://purl.obolibrary.org/obo/BFO_0000051
http://www.obofoundry.org/ro/ro.owl#proper_part_of

**Comment by wawong** [comment]
This feature has been added to the latest version.

**Comment by tgbugs** [comment]
This is great! Can you hide the the tabs when there are no matching edges?

**Comment by wawong** [comment]
Done! Test it with https://nye.crbs.ucsd.edu/NeuroKS/index.php/pages/view/NIFGA:birnlex_1489#relations

**Comment by tgbugs** [comment]
Looks like the direction of the nodes got inverted so higher level nodes are showing up lower in the hierarchy (brain appears below cerebellum).

**Comment by wawong** [comment]
Inversion problem should have been fixed. See https://nye.crbs.ucsd.edu/NeuroKS/index.php/pages/view/NIFGA:birnlex_1489
