### ISSUE TITLE
landing page for ambigious entities

### ISSUE THREAD

**Issue by tgbugs** [NeuroscienceKnowledgeSpace/KnowledgeSpace#8]
If a user enters: https://nye.crbs.ucsd.edu/SciCrunchKS/index.php/pages/view/brain it takes the user to a page for a registry resource. There are multiple entries that the user might want to choose: http://matrix.neuinfo.org:9000/scigraph/vocabulary/term/brain. We need a landing page for cases like this. This is also related to https://github.com/NeuroscienceKnowledgeSpace/KnowledgeSpace/issues/9.

**Comment by wawong** [comment]
Done and test it with https://nye.crbs.ucsd.edu/NeuroKS/index.php/pages/view/neocortex
