### ISSUE TITLE
all entities should redirect to their curie

### ISSUE THREAD

**Issue by tgbugs** [NeuroscienceKnowledgeSpace/KnowledgeSpace#9]
for example:
https://nye.crbs.ucsd.edu/SciCrunchKS/index.php/pages/view/Pyramidal_cell
needs to redirect to:
https://nye.crbs.ucsd.edu/SciCrunchKS/index.php/pages/view/NIFCELL:sao862606388

This should happen automatically for all entries that have only one result.

**Comment by wawong** [comment]
Done! Test it with https://nye.crbs.ucsd.edu/NeuroKS/index.php/pages/view/Pyramidal_cell instead.
